# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e243801adc19e3626be3586834c6a84fa193da4a3009a4a040129a2b9a57f2e0ee39a34d952d172717f7572c2ee91fed620f84e2f377bd4a1e140aa17a3caef5

test:
  secret_key_base: a2291f7c1e73ab57743a1a62279220ac7bdb3f681dffdc65cd39d99222e7267d4b35d80d853c9c87ed3f354380517d6246c52825650022de5004ec2aa949b4dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
